### ISSUE TITLE
Создание документа по шаблону и отправка пользователю для скачивания

### ISSUE THREAD

**Issue by AnastasiV** [UNIT6-open/TemplateEngine.Docx#18]
Можно ли создать документ по шаблону без сохранения на сервере, чтобы он сразу отправлялся пользователю для скачивания?
Ситуация такая - есть сайт, пользователи заходят, заполняют форму, данные сохраняются на сервере, а для пользователя формируется файл с заполненными им данными. Получается, что если одновременно для нескольких пользователей генерируется файл, то он удаляется, перезаписывается, и пользователь может получить не свои данные...

**Comment by lancheg** [comment]
Есть несколько решений данной проблемы.
Например, можно использовать временные файлы - для каждого пользователя создавать копию документа-шаблона на сервере с уникальным именем, заполнять его при помощи TemplateEngine, отправлять и затем, по необходимости, удалять.
Чтобы не создавать временных файлов на сервере, можно создавать копию файла в памяти, копируя его в новый MemoryStream - тогда для заполнения шаблона при помощи TemplateEngine нужно использовать конструктор 
public TemplateProcessor(Stream stream)

Пример: 
                 `var file = File.Open("InputTemplate.docx", FileMode.Open);`

		    using (var stream = new MemoryStream())
		    {
		        file.CopyTo(stream);
                
		        var valuesToFill = new Content(
		            // Add image
		            new ImageContent("ImageInHeader", File.ReadAllBytes("Tesla.jpg"))
		        );

		        using (var outputDocument = new TemplateProcessor(stream)
		            .SetRemoveContentControls(true))
		        {
		            outputDocument.FillContent(valuesToFill);
		            outputDocument.SaveChanges();
		        }
		    }

**Comment by AnastasiV** [comment]
@lancheg , спасибо, о временных файлах я уже думала, но как раз лучшее решение использовать потоки.

**Comment by xrkolovos** [comment]
why don't use english?
