### ISSUE TITLE
Заполнение шаблона из базы данных.

### ISSUE THREAD

**Issue by IgorDn** [UNIT6-open/TemplateEngine.Docx#19]
Скажите пожалуйста, как можно реализовать заполнение таблицы значениями из базы данных? В таблицу записывается только одно значение из базы, а не все. 
Пробую сделать так - 

```
var appVal= from value in db.ApplicantValues where value.ApplicantId == 21 select value.Value;
foreach (var v in appVal.ToList())
                {
                    var valuesToFill = new Content(
                    
                    new TableContent("table")
                    .AddRow(
                        new FieldContent("value", v)
                        )

                    );

                   
                        using (var outputDocument = new TemplateProcessor(Server.MapPath("Test.docx"))
                                    .SetRemoveContentControls(false))
                        {
                            outputDocument.FillContent(valuesToFill);
                            outputDocument.SaveChanges();
                        }
                    

                }
```

**Comment by lancheg** [comment]
Добрый день!
В каждой итерации Вы перезаписываете файл, заполняя его лишь одним значением с текущей итерации.
Чтобы в таблицу добавлялись все значения из db.ApplicantValues, нужно написать примерно следующее:

var appVal= from value in db.ApplicantValues where value.ApplicantId == 21 select value.Value;

var tableContent = new TableContent("table");

foreach (var v in appVal.ToList())
{
	tableContent.AddRow(new FieldContent("value", v));
}

var valuesToFill = new Content(tableContent);
      
using (var outputDocument = new TemplateProcessor(Server.MapPath("Test.docx"))
	.SetRemoveContentControls(false))
{
    outputDocument.FillContent(valuesToFill);
    outputDocument.SaveChanges();
}

**Comment by IgorDn** [comment]
Спасибо за помощь) Теперь работает.
