### ISSUE TITLE
How to insert line break?

### ISSUE THREAD

**Issue by fabiolima1** [UNIT6-open/TemplateEngine.Docx#2]
Need a way to insert line breaks (paragraph) in a FieldContent, as using \r\n in the string does not work.

**Comment by xrkolovos** [comment]
Is there any way to do this?

**Comment by xrkolovos** [comment]
i found a solution.
in file XElementExtensions.cs i added a method ReplaceNewLinesWithBreaks(). Also in method ReplaceContentControlWithNewValue i added a call at the end of it ReplaceNewLinesWithBreaks(sdt).

`public static void ReplaceNewLinesWithBreaks(XElement xElem)
        {
            var textWithBreaks = xElem.Descendants(W.t).Where(t => t.Value.Contains("\\r\\n"));
            foreach (var textWithBreak in textWithBreaks)
            {
                var text = textWithBreak.Value;
                var split = text.Replace("\\r\\n", "\\n").Split(new[] { "\\n" }, StringSplitOptions.None);

                textWithBreak.Value = string.Empty;
                foreach (var s in split) {
                    textWithBreak.Add(new XElement(W.t, s));
                    textWithBreak.Add(new XElement(W.br));
                }
                textWithBreak.Descendants(W.br).Last().Remove();
            }
        }`

in internal static class W i also added this
public static XName br = w + "br";

**Comment by lancheg** [comment]
Thank you for your code. The code has been added to the repository. 
It will be available in the next releases.

**Comment by windofny** [comment]
Hello! But what to if I need to have a real Paragraph ?
I try to use code with additional link to sdtContent, but it breaks document and Word cant open it:
public static void ReplaceNewLinesWithBreaks(XElement xElem,XElement sdtContent)
{
var textWithBreaks = xElem.Descendants(W.t).Where(t => t.Value.Contains("\r\n"));
foreach (var textWithBreak in textWithBreaks)
{
var text = textWithBreak.Value;
var split = text.Replace("\r\n", "\n").Split(new[] { "\n" }, StringSplitOptions.None);
textWithBreak.Value = string.Empty;
foreach (var s in split) {
sdtContent.Add(new XElement(W.p, new XElement(W.r, new XElement(W.t, s))));
 }
textWithBreak.Descendants(W.br).Last().Remove();
}
}
 textWithBreaks.Remove();
}
Can you help to resolve this issue ?

**Comment by QuantumHawk** [comment]
Hi! I have exectly same issue in Linux, with libraoffice, can you help me?
