### ISSUE TITLE
Deploying DLL to GAC

### ISSUE THREAD

**Issue by AndrewNikolin** [UNIT6-open/TemplateEngine.Docx#20]
Hello! There is a problem when deploying the DLL of your project (installed via NuGet) to GAC. Using Visual Studio deployment (deploying SharePoint solution) fails with error "Error occurred in deployment step 'Add Solution': This solution contains one or more assemblies targeted for the global assembly cache. You should use a strong name for any assembly that will be in the global assembly cache."
Then, when I tried to use Gacutil I've got "Failure adding assembly to the cache: Attempt to install an assembly without a strong name". According to Google this can be fixed with signing the project of DLL (project properties -> Signing tab). For myself I've got it fixed with signing the project of your library and rebuilding it.

**Comment by lancheg** [comment]
Hello, @AndrewNikolin !

We signed dll in the nuget package. You can deploy our dll to GAC now.

Thank you!
