### ISSUE TITLE
Duplicates of tests found by PVS-Studio

### ISSUE THREAD

**Issue by Neiromaster** [UNIT6-open/TemplateEngine.Docx#29]
V3013 It is odd that the body of ‘RepeatContentConstructorWithNameAndEnumerableFieldContent_FillsNameAndItems’ function is fully equivalent to the body of ‘RepeatContentConstructorWithNameAndEnumerableListItemContent_FillsNameAndItems’ function. **RepeatContentTests.cs**

V3013 It is odd that the body of ‘ListContentConstructorWithNameAndEnumerableFieldContent_FillsNameAndItems’ function is fully equivalent to the body of ‘ListContentConstructorWithNameAndEnumerableListItemContent_FillsNameAndItems’ function. **ListContentTests.cs**

**Comment by abatar1** [comment]
Fixed.
