### ISSUE TITLE
Is NuGet Updated?

### ISSUE THREAD

**Issue by ealbert** [UNIT6-open/TemplateEngine.Docx#3]
I just added the library to my project using NuGet (version 1.1.1) and when I execute the following code:

        public static void CopyTemplate()
        {
            File.Copy("TemplateBasic.docx", "outputPath.docx", true);
            var valuesToFill = new Content(
                new FieldContent("ReportDate", DateTime.Now.ToString()));

            using (var outputDoc = new TemplateProcessor("OutputDoc.docx"))
            {
                outputDoc.FillContent(valuesToFill);
                outputDoc.SaveChanges();
            }
        }

It fails indicating a null reference in the LoadPart method.
The template that I use is very basic, it only contains a field.
If I get the latest code from GitHub instead, everything works. 
Is the NuGet library out of sync?

**Comment by AIVolkov** [comment]
NuGet package 1.1.2 should be synced with GitHub code.
Thanks.

**Comment by ealbert** [comment]
Thanks
