### ISSUE TITLE
Error 'Sequence contains no elements' when TableContent have not rows. (count == 0)

### ISSUE THREAD

**Issue by ildarnm** [UNIT6-open/TemplateEngine.Docx#35]
callstack:  

> at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
>    at TemplateEngine.Docx.Processors.TableProcessor.GetPrototype(XContainer tableContentControl, IEnumerable`1 fieldNames)
>    at TemplateEngine.Docx.Processors.TableProcessor.FillContent(XContainer contentControl, IContentItem item)
>    at TemplateEngine.Docx.Processors.TableProcessor.FillContent(XElement contentControl, IEnumerable`1 items)
>    at TemplateEngine.Docx.Processors.ContentProcessor.FillContent(XElement content, IEnumerable`1 data)
>    at TemplateEngine.Docx.Processors.ContentProcessor.FillContent(XElement content, Content data)
>    at TemplateEngine.Docx.TemplateProcessor.FillContent(Content content)

**Comment by abatar1** [comment]
Fixed it.

**Comment by ildarnm** [comment]
@abatar1 Bug in TableProcessor method GetPrototype line where Enumerable.First
When not rows it return error

**Comment by abatar1** [comment]
Could you please write your code where you construct Content to be filled in TemplateProcessor? 
I don't get this error when I only try to create Content with TableContent with no rows.

**Comment by ildarnm** [comment]
```
using (var document = new TemplateProcessor("Assets/OutputDocument.docx")
                .SetRemoveContentControls(true))
            {
                var content = new Content(new TableContent("TestTable"));

                document.FillContent(content);
                document.SaveChanges();
            }
```

In template should be token "TestTable".

**Comment by ildarnm** [comment]
@abatar1 I figured out. It is happens only if use Repeat Section Content Control in word
