### ISSUE TITLE
Десериализация Content

### ISSUE THREAD

**Issue by Drinker5** [UNIT6-open/TemplateEngine.Docx#4]
Объект Content отлично сериализуется в json, но десериализовать его не получается из за интерфейсов в конструкторе.
Я думаю было бы отлично реализовать что-нибудь типа ```new Content(json)```.
Это значительно расширит возможности применения библиотеки.
А что думаете Вы?

**Comment by AIVolkov** [comment]
А конструктора без параметров не достаточно для этого?

**Comment by Drinker5** [comment]
Ну да, достаточно реализовать свой JsonConverter включив в сериализацию TypeNameHandling.

**Comment by lancheg** [comment]
Добавлена возможность сериализации в Json объекта класса Content. 
Данный функционал будет доступен в следующем релизе.
