### ISSUE TITLE
Cannot install NuGet package in project targetting .NET 4.5.1

### ISSUE THREAD

**Issue by chippy** [UNIT6-open/TemplateEngine.Docx#48]
When trying to install the NuGet Package I receive the message "Could not install package 'TemplateEngine.Docx 1.1.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author."

Is this really not compatible with this version?

**Comment by tomek14** [comment]
This is .NETStandard 2.0 library and it won't be working on .NET Framework 4.5.1 (https://docs.microsoft.com/pl-pl/dotnet/standard/net-standard). You should re-target to at least 4.6.1, or better to 4.7.2.

**Comment by chippy** [comment]
Closed
