### ISSUE TITLE
Any support for picture content controls?

### ISSUE THREAD

**Issue by ozzioma** [UNIT6-open/TemplateEngine.Docx#8]
Hi,
Your library looks cool!
However, I need to be able to replace images in my templates.
Any support for picture content controls?

Thanks,
Ozzy

**Comment by JakubPetr** [comment]
+1

**Comment by JakubPetr** [comment]
I ended up writing support for this myself https://github.com/UNIT6-open/TemplateEngine.Docx/pull/9. It's based on Adams briliant answer http://stackoverflow.com/questions/2810138/replace-image-in-word-doc-using-openxml.

**Comment by ChrisFeldmeier** [comment]
@JakubPetr did you have implemented images to the Engine.Docx yet???

**Comment by JakubPetr** [comment]
Yes, the pull request has not been merged yet. But you can take it from my fork: https://github.com/JakubPetr/TemplateEngine.Docx

**Comment by lancheg** [comment]
Thanks! It will be available in the next release.
